// Liste des pays avec indicatif téléphonique (France en premier, puis ordre alphabétique)
// Source: codes d'appel internationaux ITU
export const COUNTRY_DIAL_LIST = [
  { name: "France", dial: "+33" },
  { name: "Afghanistan", dial: "+93" },
  { name: "Afrique du Sud", dial: "+27" },
  { name: "Albanie", dial: "+355" },
  { name: "Algérie", dial: "+213" },
  { name: "Allemagne", dial: "+49" },
  { name: "Andorre", dial: "+376" },
  { name: "Angola", dial: "+244" },
  { name: "Anguilla", dial: "+1264" },
  { name: "Antigua-et-Barbuda", dial: "+1268" },
  { name: "Arabie saoudite", dial: "+966" },
  { name: "Argentine", dial: "+54" },
  { name: "Arménie", dial: "+374" },
  { name: "Aruba", dial: "+297" },
  { name: "Australie", dial: "+61" },
  { name: "Autriche", dial: "+43" },
  { name: "Azerbaïdjan", dial: "+994" },
  { name: "Bahamas", dial: "+1242" },
  { name: "Bahreïn", dial: "+973" },
  { name: "Bangladesh", dial: "+880" },
  { name: "Barbade", dial: "+1246" },
  { name: "Belgique", dial: "+32" },
  { name: "Belize", dial: "+501" },
  { name: "Bénin", dial: "+229" },
  { name: "Bermudes", dial: "+1441" },
  { name: "Bhoutan", dial: "+975" },
  { name: "Biélorussie", dial: "+375" },
  { name: "Bolivie", dial: "+591" },
  { name: "Bosnie-Herzégovine", dial: "+387" },
  { name: "Botswana", dial: "+267" },
  { name: "Brésil", dial: "+55" },
  { name: "Brunei", dial: "+673" },
  { name: "Bulgarie", dial: "+359" },
  { name: "Burkina Faso", dial: "+226" },
  { name: "Burundi", dial: "+257" },
  { name: "Cambodge", dial: "+855" },
  { name: "Cameroun", dial: "+237" },
  { name: "Canada", dial: "+1" },
  { name: "Cap-Vert", dial: "+238" },
  { name: "Chili", dial: "+56" },
  { name: "Chine", dial: "+86" },
  { name: "Chypre", dial: "+357" },
  { name: "Colombie", dial: "+57" },
  { name: "Comores", dial: "+269" },
  { name: "Congo", dial: "+242" },
  { name: "Congo (RDC)", dial: "+243" },
  { name: "Corée du Nord", dial: "+850" },
  { name: "Corée du Sud", dial: "+82" },
  { name: "Costa Rica", dial: "+506" },
  { name: "Côte d'Ivoire", dial: "+225" },
  { name: "Croatie", dial: "+385" },
  { name: "Cuba", dial: "+53" },
  { name: "Curaçao", dial: "+599" },
  { name: "Danemark", dial: "+45" },
  { name: "Djibouti", dial: "+253" },
  { name: "Dominique", dial: "+1767" },
  { name: "Égypte", dial: "+20" },
  { name: "Émirats arabes unis", dial: "+971" },
  { name: "Équateur", dial: "+593" },
  { name: "Érythrée", dial: "+291" },
  { name: "Espagne", dial: "+34" },
  { name: "Estonie", dial: "+372" },
  { name: "Eswatini", dial: "+268" },
  { name: "États-Unis", dial: "+1" },
  { name: "Éthiopie", dial: "+251" },
  { name: "Fidji", dial: "+679" },
  { name: "Finlande", dial: "+358" },
  { name: "Gabon", dial: "+241" },
  { name: "Gambie", dial: "+220" },
  { name: "Géorgie", dial: "+995" },
  { name: "Ghana", dial: "+233" },
  { name: "Gibraltar", dial: "+350" },
  { name: "Grèce", dial: "+30" },
  { name: "Grenade", dial: "+1473" },
  { name: "Groenland", dial: "+299" },
  { name: "Guadeloupe", dial: "+590" },
  { name: "Guam", dial: "+1671" },
  { name: "Guatemala", dial: "+502" },
  { name: "Guinée", dial: "+224" },
  { name: "Guinée-Bissau", dial: "+245" },
  { name: "Guinée équatoriale", dial: "+240" },
  { name: "Guyana", dial: "+592" },
  { name: "Guyane française", dial: "+594" },
  { name: "Haïti", dial: "+509" },
  { name: "Honduras", dial: "+504" },
  { name: "Hong Kong", dial: "+852" },
  { name: "Hongrie", dial: "+36" },
  { name: "Île Norfolk", dial: "+672" },
  { name: "Îles Åland", dial: "+358" },
  { name: "Îles Caïmans", dial: "+1345" },
  { name: "Îles Cook", dial: "+682" },
  { name: "Îles Féroé", dial: "+298" },
  { name: "Îles Malouines", dial: "+500" },
  { name: "Îles Mariannes du Nord", dial: "+1670" },
  { name: "Îles Marshall", dial: "+692" },
  { name: "Îles Salomon", dial: "+677" },
  { name: "Îles Turques-et-Caïques", dial: "+1649" },
  { name: "Îles Vierges britanniques", dial: "+1284" },
  { name: "Îles Vierges des États-Unis", dial: "+1340" },
  { name: "Inde", dial: "+91" },
  { name: "Indonésie", dial: "+62" },
  { name: "Irak", dial: "+964" },
  { name: "Iran", dial: "+98" },
  { name: "Irlande", dial: "+353" },
  { name: "Islande", dial: "+354" },
  { name: "Israël", dial: "+972" },
  { name: "Italie", dial: "+39" },
  { name: "Jamaïque", dial: "+1876" },
  { name: "Japon", dial: "+81" },
  { name: "Jersey", dial: "+44" },
  { name: "Jordanie", dial: "+962" },
  { name: "Kazakhstan", dial: "+7" },
  { name: "Kenya", dial: "+254" },
  { name: "Kirghizistan", dial: "+996" },
  { name: "Kiribati", dial: "+686" },
  { name: "Kosovo", dial: "+383" },
  { name: "Koweït", dial: "+965" },
  { name: "Laos", dial: "+856" },
  { name: "Lesotho", dial: "+266" },
  { name: "Lettonie", dial: "+371" },
  { name: "Liban", dial: "+961" },
  { name: "Liberia", dial: "+231" },
  { name: "Libye", dial: "+218" },
  { name: "Liechtenstein", dial: "+423" },
  { name: "Lituanie", dial: "+370" },
  { name: "Luxembourg", dial: "+352" },
  { name: "Macao", dial: "+853" },
  { name: "Macédoine du Nord", dial: "+389" },
  { name: "Madagascar", dial: "+261" },
  { name: "Malaisie", dial: "+60" },
  { name: "Malawi", dial: "+265" },
  { name: "Maldives", dial: "+960" },
  { name: "Mali", dial: "+223" },
  { name: "Malte", dial: "+356" },
  { name: "Maroc", dial: "+212" },
  { name: "Martinique", dial: "+596" },
  { name: "Maurice", dial: "+230" },
  { name: "Mauritanie", dial: "+222" },
  { name: "Mayotte", dial: "+262" },
  { name: "Mexique", dial: "+52" },
  { name: "Micronésie", dial: "+691" },
  { name: "Moldavie", dial: "+373" },
  { name: "Monaco", dial: "+377" },
  { name: "Mongolie", dial: "+976" },
  { name: "Monténégro", dial: "+382" },
  { name: "Montserrat", dial: "+1664" },
  { name: "Mozambique", dial: "+258" },
  { name: "Myanmar", dial: "+95" },
  { name: "Namibie", dial: "+264" },
  { name: "Nauru", dial: "+674" },
  { name: "Népal", dial: "+977" },
  { name: "Nicaragua", dial: "+505" },
  { name: "Niger", dial: "+227" },
  { name: "Nigeria", dial: "+234" },
  { name: "Niue", dial: "+683" },
  { name: "Norvège", dial: "+47" },
  { name: "Nouvelle-Calédonie", dial: "+687" },
  { name: "Nouvelle-Zélande", dial: "+64" },
  { name: "Oman", dial: "+968" },
  { name: "Ouganda", dial: "+256" },
  { name: "Ouzbékistan", dial: "+998" },
  { name: "Pakistan", dial: "+92" },
  { name: "Palaos", dial: "+680" },
  { name: "Palestine", dial: "+970" },
  { name: "Panama", dial: "+507" },
  { name: "Papouasie-Nouvelle-Guinée", dial: "+675" },
  { name: "Paraguay", dial: "+595" },
  { name: "Pays-Bas", dial: "+31" },
  { name: "Pérou", dial: "+51" },
  { name: "Philippines", dial: "+63" },
  { name: "Pologne", dial: "+48" },
  { name: "Polynésie française", dial: "+689" },
  { name: "Porto Rico", dial: "+1787" },
  { name: "Portugal", dial: "+351" },
  { name: "Qatar", dial: "+974" },
  { name: "République centrafricaine", dial: "+236" },
  { name: "République dominicaine", dial: "+1809" },
  { name: "République tchèque", dial: "+420" },
  { name: "La Réunion", dial: "+262" },
  { name: "Roumanie", dial: "+40" },
  { name: "Royaume-Uni", dial: "+44" },
  { name: "Russie", dial: "+7" },
  { name: "Rwanda", dial: "+250" },
  { name: "Saint-Barthélemy", dial: "+590" },
  { name: "Saint-Christophe-et-Niévès", dial: "+1869" },
  { name: "Sainte-Hélène", dial: "+290" },
  { name: "Sainte-Lucie", dial: "+1758" },
  { name: "Saint-Marin", dial: "+378" },
  { name: "Saint-Martin", dial: "+590" },
  { name: "Saint-Pierre-et-Miquelon", dial: "+508" },
  { name: "Saint-Vincent-et-les-Grenadines", dial: "+1784" },
  { name: "Salvador", dial: "+503" },
  { name: "Samoa", dial: "+685" },
  { name: "Samoa américaines", dial: "+1684" },
  { name: "Sao Tomé-et-Príncipe", dial: "+239" },
  { name: "Sénégal", dial: "+221" },
  { name: "Serbie", dial: "+381" },
  { name: "Seychelles", dial: "+248" },
  { name: "Sierra Leone", dial: "+232" },
  { name: "Singapour", dial: "+65" },
  { name: "Sint Maarten", dial: "+1721" },
  { name: "Slovaquie", dial: "+421" },
  { name: "Slovénie", dial: "+386" },
  { name: "Somalie", dial: "+252" },
  { name: "Soudan", dial: "+249" },
  { name: "Soudan du Sud", dial: "+211" },
  { name: "Sri Lanka", dial: "+94" },
  { name: "Suède", dial: "+46" },
  { name: "Suisse", dial: "+41" },
  { name: "Suriname", dial: "+597" },
  { name: "Syrie", dial: "+963" },
  { name: "Tadjikistan", dial: "+992" },
  { name: "Taïwan", dial: "+886" },
  { name: "Tanzanie", dial: "+255" },
  { name: "Tchad", dial: "+235" },
  { name: "Thaïlande", dial: "+66" },
  { name: "Timor oriental", dial: "+670" },
  { name: "Togo", dial: "+228" },
  { name: "Tokelau", dial: "+690" },
  { name: "Tonga", dial: "+676" },
  { name: "Trinité-et-Tobago", dial: "+1868" },
  { name: "Tunisie", dial: "+216" },
  { name: "Turkménistan", dial: "+993" },
  { name: "Turquie", dial: "+90" },
  { name: "Tuvalu", dial: "+688" },
  { name: "Ukraine", dial: "+380" },
  { name: "Uruguay", dial: "+598" },
  { name: "Vanuatu", dial: "+678" },
  { name: "Vatican", dial: "+379" },
  { name: "Venezuela", dial: "+58" },
  { name: "Viêt Nam", dial: "+84" },
  { name: "Wallis-et-Futuna", dial: "+681" },
  { name: "Yémen", dial: "+967" },
  { name: "Zambie", dial: "+260" },
  { name: "Zimbabwe", dial: "+263" },
];
